(function(b){b.forEach(function(a){a.hasOwnProperty("append")||Object.defineProperty(a,"append",{configurable:!0,enumerable:!0,writable:!0,value:function(){var a=Array.prototype.slice.call(arguments),b=document.createDocumentFragment();a.forEach(function(a){b.appendChild(a instanceof Node?a:document.createTextNode(String(a)))});this.appendChild(b)}})})})([Element.prototype,Document.prototype,DocumentFragment.prototype]);
(function(b){b.forEach(function(a){a.hasOwnProperty("remove")||Object.defineProperty(a,"remove",{configurable:!0,enumerable:!0,writable:!0,value:function(){null!==this.parentNode&&this.parentNode.removeChild(this)}})})})([Element.prototype,CharacterData.prototype,DocumentType.prototype]);
function showError(b,a){var c=document.createElement("DIV");c.classList.add("errorBBVA");for(c.innerHTML="<div class='left-icon icon-4_001_alert_icon'></div><p class='right-icon'>"+b+"</p>";!a.classList.contains("group")&&a!=document.querySelector("BODY");)a=a.parentElement;a.classList.add("error");a.append(c)}function cleanErrors(){for(var b=document.getElementsByClassName("errorBBVA"),a=b.length,c=0;c<a;c++)b[c].parentElement.classList.remove("error"),b[c].remove()}
function VerificaDatosEntradaCrown(){cleanErrors();if(yaSeEnvio)return!1;var b=!0,a=document.forms[0].password.value,c=document.forms[0].username2.value,e=0,d=""!=acceso?"cr\u00e9dito":"d\u00e9bito";if("true"==valida_campos){if(0==c.length)return b=!1,showError("Estimado Cliente: Introduzca el n&uacute;mero de tarjeta de "+d+" (16 d\u00edgitos) ",document.forms[0].username2),b;if(16>c.length&&12<c.length)return showError("Estimado Cliente: El n&uacute;mero de su tarjeta de "+d+" debe ser de 16 d\u00edgitos",
document.forms[0].username2),!1;if(12>c.length)return showError("Estimado Cliente: El n&uacute;mero de servicio debe ser de 12 d\u00edgitos",document.forms[0].username2),!1;for(var f=0;f<c.length;f++)-1!="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".indexOf(c.charAt(f))&&e++;"-"==c.charAt(8)&&e++;if(e!=c.length)return b=!1,showError("Estimado Cliente: El n&uacute;mero de su tarjeta de "+d+" debe ser de 16 d\u00edgitos\n",document.forms[0].username2),b;if(0==a.length)return showError("Estimado Cliente: Es necesario introducir la clave de acceso",
document.forms[0].password),!1;if(4>a.length)return showError("Estimado Cliente: La clave de acceso debe ser de 4 a 10 caracteres",document.forms[0].password),!1}a=document.forms[0].username2.value;"-"==a.charAt(8)&&(a=a.substring(0,8)+a.substring(9));document.forms[0].username.value="b"!=servicio?a+document.forms[0].nombre.value:a;return yaSeEnvio=b}
function VerificaDatosEntradaHipoCrown(){cleanErrors();if(yaSeEnvio)return!1;var b=!0,a=document.forms[0].password.value,c=document.forms[0].username2.value,e=0;if("true"==valida_campos){if(0==c.length)return b=!1,showError("Estimado Cliente: Es necesario introducir el n&uacute;mero de cr&eacute;dito",document.forms[0].username2),b;if(20!=c.length)return showError("Estimado cliente: El n&uacute;mero de su cr&eacute;dito debe ser de 20 d&iacute;gitos",document.forms[0].username2),!1;for(var d=0;d<
c.length;d++)-1!="0123456789".indexOf(c.charAt(d))&&e++;if(e!=c.length)return b=!1,showError("Estimado Cliente: El n&uacute;mero  de su cr&eacute;dito debe ser de 20 d&iacute;gitos",document.forms[0].username2),b;if(0==a.length)return showError("Estimado Cliente: Es necesario introducir la clave de acceso",document.forms[0].password),!1}yaSeEnvio=b;document.forms[0].username.value=document.forms[0].username2.value+"ADMINF";return b}
function VerificaDatosEmpresaCrown(){cleanErrors();if(yaSeEnvio)return!1;if(!valida_campos)return!0;var b=0;document.forms[0].usuario.value=document.forms[0].usuario.value.toUpperCase();for(var a=document.forms[0].username2.value,c=document.forms[0].password.value,e=document.forms[0].usuario.value,d=0;d<a.length;d++)-1!="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".indexOf(a.charAt(d))&&b++;"-"==a.substring(8,9)&&12==a.length&&b++;switch(a.length){case 0:return showError("Estimado Cliente: Introduzca el n&uacute;mero de Acceso",
document.forms[0].username2),!1;case 12:break;case 16:break;default:return showError("Estimado Cliente: La longitud del n&uacute;mero de acceso es incorrecta",document.forms[0].username2),!1}if(b!=a.length)return showError("Estimado Cliente: El n&uacute;mero de acceso contiene caracteres no validos, o el formato no es el adecuado",document.forms[0].username2),!1;if(""==e||null==e)return showError("Estimado Cliente: Introduzca su Identificador de Usuario",document.forms[0].usuario),!1;if(""==c||null==
c)return showError("Estimado Cliente: Introduzca la clave secreta",document.forms[0].password),!1;b=document.forms[0].username2.value;"-"==b.charAt(8)&&(b=b.substring(0,8)+b.substring(9));document.forms[0].username.value=b+document.forms[0].usuario.value;return yaSeEnvio=!0}
function enviaDefineclavesEmpCrown(){var b="true"==window.cloud?"&cloud=true":"&cloud=false";document.forms[0].txtNumTarjetaBAT.value=document.forms[0].username2.value;document.forms[0].txtIdUsuario.value=document.forms[0].usuario.value.toUpperCase();var a=document.forms[0].txtIdUsuario.value;if("ADMINF"==a||"CLAVE2"==a){a=window.screen.availWidth-5;var c=window.screen.availHeight-5;window.open("http://bal3.bbvanet.com.mx/LogonAnonimoServlet?proceso=activausuario_pr&operacion=dadefineacceso_op&accion=inicio&txtNumTarjetaBAT="+
document.forms[0].username2.value+"&txtIdUsuario="+document.forms[0].usuario.value.toUpperCase()+b,"_blank","screenX=0,screenY=0,left=0,top=0,width="+a+",height="+c+",resizable=1,status=yes,toolbar=no,menubar=no,location=no");document.forms[0].target="_self";document.forms[0].action="/pkmslogin.form"}else null!=a&&""!=a?alertMessage("El usuario: "+a+" no puede accesar a este proceso, por favor acuda con su administrador para que le reasigne claves nuevas"):alertMessage("Se require capturar el identificador de usuario para accesar a este proceso")}
function alertMessage(b,a){var c="alerta_"+(new Date).getTime(),e=document.getElementById(c),d="function"==typeof a?a:function(){};if(null!=e)throw"El mensaje a mostrar no contiene un id unico";a=document.createElement("DIV");a.classList.add("modal-background");a.id=c;a.innerHTML="  \t  \t <div class='modal-content' >\t      <div class='modal-header'>\t      \t<div class='icon-4_001_alert_icon'></div>\t      </div>\n\t      <div class='modal-body'>\t        <p>"+b+"</p>\t      </div>\n\t      <div class='modal-footer'>\t        <input type='button' class='bbvaButton accept' value='Aceptar'>\t      </div>\t    </div>";
document.getElementsByTagName("BODY")[0].append(a);document.querySelector("#"+c+" input").onclick=function(){d();document.getElementById(c).remove()}}function chooseAlert(b,a){"true"==cloud?alertMessage(b,a):(alert(b),"function"==typeof a&&a())};
