var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");function validaClaveAcceso(a){cleanError(a);var b=a.target.value;"true"==valida_campos&&(0==b.length?showError("Es necesario introducir la clave de acceso",a.target):4>b.length&&showError("La clave de acceso debe ser de 4 a 10 caracteres",a.target))}
function validaUserNull(a){cleanError(a);var b=a.target.value;""!=b&&null!=b||showError("Introduce tu Identificador de Usuario",a.target)}function validaPasswordNull(a){cleanError(a);var b=a.target.value;""!=b&&null!=b||showError("Introduce la clave secreta",a.target)}
function validaUserNameNumeric(a){var b=a.target.value,c=0;cleanError(a);if("true"==valida_campos)if(0==b.length)showError("Introduce el n&uacute;mero de cr&eacute;dito",a.target);else if(20!=b.length)showError("El n&uacute;mero de tu cr&eacute;dito debe ser de 20 d&iacute;gitos",a.target);else{for(var d=0;d<b.length;d++)-1!="0123456789".indexOf(b.charAt(d))&&c++;c!=b.length&&showError("El n&uacute;mero  de tu cr&eacute;dito debe ser de 20 d&iacute;gitos",a.target)}}
function cleanError(a){a=$(a.target.parentElement).find(".errorBBVA");for(var b=a.length,c=0;c<b;c++)a[c].parentElement.classList.remove("error"),a[c].remove()}
function validaUserNameAlphaNumeric(a){cleanError(a);var b=a.target.value,c=0,d=""!=acceso?"cr\u00e9dito":"d\u00e9bito";if("true"==valida_campos)if(0==b.length)showError("Introduce el n&uacute;mero de tarjeta de "+d+" (16 d\u00edgitos) ",a.target);else if(16>b.length&&12<b.length)showError("El n&uacute;mero de tu tarjeta de "+d+" debe ser de 16 d\u00edgitos",a.target);else if(12>b.length)showError("El n&uacute;mero de servicio debe ser de 12 d\u00edgitos",a.target);else{for(var e=0;e<b.length;e++)-1!=
"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".indexOf(b.charAt(e))&&c++;"-"==b.charAt(8)&&c++;c!=b.length&&showError("El n&uacute;mero de tu tarjeta de "+d+" debe ser de 16 d\u00edgitos\n",a.target)}}
window.addEventListener("load",function(){jQuery("#CodTarj").dPassword();jQuery("#password_username2").dPassword();var a=document.getElementById("password_CodTarj");void 0!=a&&null!=a&&"true"==cloud&&(document.getElementById("password_CodTarj").required=!0);a=document.getElementById("password_password_username2");void 0!=a&&null!=a&&"true"==cloud&&(document.getElementById("password_password_username2").required=!0);attachValidations()});
function attachValidations(){if("true"==valida_campos)if("portallSat"===crownInputValidations||"sat"===crownInputValidations||"responsivePersonas"==crownInputValidations)document.getElementById("password_password_username2").addEventListener("blur",function(a){a={};a.target=document.forms[0].username2;validaUserNameAlphaNumeric(a)}),document.forms[0].password.addEventListener("blur",validaClaveAcceso);else if("mortage"===crownInputValidations)try{document.getElementById("password_password_username2").addEventListener("blur",
function(a){a={};a.target=document.forms[0].username2;validaUserNameNumeric(a)}),document.forms[0].password.addEventListener("blur",validaPasswordNull)}catch(a){}else"responsiveEmpresa"===crownInputValidations&&(document.getElementById("password_password_username2").addEventListener("blur",function(a){a={};a.target=document.forms[0].username2;validaUserNameAlphaNumeric(a)}),document.forms[0].password.addEventListener("blur",validaPasswordNull),document.forms[0].usuario.addEventListener("blur",validaUserNull))}
;
